/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    Users: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    WebApp: {
      type: "sst.aws.SvelteKit";
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
